[build]
  base = "music-client"
  command = "npm run build"
  publish = "dist"  # ✅ This is the correct relative path inside "music-client"
  functions = "../netlify/functions"  # If your functions are outside "music-client"
